cc_library(
    name = "multipointer",
    hdrs = ["multipointer.hpp"],
)

cc_library(
    name = "soa",
    hdrs = ["soa.hpp"],
    deps = [
        "multipointer",
    ],
)


package(
    default_visibility = ["//visibility:public"],
)
